### PR TITLE
Development Setup

### PR DESCRIPTION
**Pull request by johnpaulada**
# Development Setup

## 🐶 Why? (Rationale)
We need a quick way to spin up all our containerized application components and be able to develop on them quickly despite them being containerized (without unnecessary container rebuilds).

## ✅ What? (Changes)
- Setup initial frontend web code (Astro)
- Setup initial backend web code (Express)
- Setup database instance (Postgres)
- Setup development tooling and versioning (DevBox + asdf)
- Setup containerization setup for development (Docker Compose)
- Setup file sync and update while services are running as containers (Tilt)
- Setup initial architecture diagrams, docs, and architectural decision records (ADRs)
- Setup general editor settings so we uniform
- Setup recommended VS Code extensions
- Setup TypeScript for Express (Astro has it already IIRC)

### 🏃 ... do we run this?
- We have instructions in the `README.md` but in short:
1. Install Docker and DevBox.
2. Run `devbox shell` to enter the isolated dev environment and automatically install dependencies.
3. (Optional) Run `cp .env.sample > .env` then fill in with values
4. Finally, just run `tilt up` to start all services, and you should be golden 🎉  

### 📺 ... does it look? (Screenshots, etc.)

_Initial Frontend Setup_
Screenshot 2023-02-26 at 3 20 19 AM

_Initial Backend Setup_
Screenshot 2023-02-26 at 3 21 05 AM

_See all the logs of all services in one dashboard_
Screenshot 2023-02-26 at 3 11 13 AM

_Initial Architecture Diagram_
Screenshot 2023-02-26 at 3 18 31 AM

_ADR Proposal_
Screenshot 2023-02-26 at 3 19 47 AM

---

## 🗒️  Notes
Containerization honestly makes more sense with development, especially coz we have different machines.
For deployment, it's much more efficient to deploy to a PaaS solution on any cloud -- that way we don't experience the overhead as an effect of containerization.

### CODE REVIEW

**Review by Neferpitooou — APPROVED** [review]
Wow nice JP... Basically most or all startups are already here. We could learn a lot from here😊. 

Thanks JP.

**Review by shannaurelle — APPROVED** [review]
Thank you JP! The initial request looks promising for learning experience. The resources for Astro are already present and it should help others commit into the community repository.

**Comment by khiromoshito** [comment]
Hi @johnpaulada, thanks for this initial PR. Although, I believe the `src/api/public/`directory can already be removed since we will not be performing static web rendering from the backend. Other than that, LGTM!

**Review by khiromoshito — CHANGES_REQUESTED** [review]
Hi @johnpaulada, thanks for this initial PR. Although, I believe the `src/api/public/` directory can already be removed since we will not be performing static web rendering from the backend. Other than that, LGTM!

**Review by Neferpitooou — APPROVED** [review]
Approved and we could merge the request so that we can have now a base line. Then for next MRs.

**Comment by Neferpitooou** [comment]
Guys lets Merge the PR so that we could have a base line and make other MR/PR small..

**Comment by johnpaulada** [comment]
> Hi @johnpaulada, thanks for this initial PR. Although, I believe the `src/api/public/` directory can already be removed since we will not be performing static web rendering from the backend. Other than that, LGTM!

Gotcha. Alright. Let me remove this, and will check if there aren't any more references to it. Nice catch!

**Review by Neferpitooou — APPROVED** [review]

**Review by khiromoshito — APPROVED** [review]
LGTM!

**Pull request merged**
