### PR TITLE
Deploy to Staging

### PR DESCRIPTION
**Pull request by johnpaulada**
# Development Setup

## 🐶 Why? (Rationale)
Currently setting up a deploy to staging so we can test there and then swap to production.

## ✅ What? (Changes)
- Created specific script instead of Azure's generic Node script

### 🏃 ... do we run this?
This is triggered when pushing to `master`.
Or manually run in Github's Actions tab.

### 📺 ... does it look? (Screenshots, etc.)
N/A

### CODE REVIEW

**Review by shannaurelle — DISMISSED** [review]
Noted. Thanks JP!

**Comment by Kriztoper** [comment]
> Azure Static Web Apps: Your stage site is ready! Visit it here: https://wonderful-moss-0d6ec0610-2.centralus.2.azurestaticapps.net

Noiceeee, is this final already? Or will you still be pushing new commits? @johnpaulada

**Comment by johnpaulada** [comment]
> 

@Kriztoper I'm done with my changes! :D

**Review by Kriztoper — APPROVED** [review]
💪

**Review by shannaurelle — APPROVED** [review]
Thanks JP!

**Pull request merged**
